/*----- PROTECTED REGION ID(Spellman_SLM_PSClass.h) ENABLED START -----*/
//=============================================================================
//
// file :        Spellman_SLM_PSClass.h
//
// description : Include for the Spellman_SLM_PS root class.
//               This class is the singleton class for
//                the Spellman_SLM_PS device class.
//               It contains all properties and methods which the 
//               Spellman_SLM_PS requires only once e.g. the commands.
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef Spellman_SLM_PSClass_H
#define Spellman_SLM_PSClass_H

#include <tango.h>
#include <Spellman_SLM_PS.h>


/*----- PROTECTED REGION END -----*/	//	Spellman_SLM_PSClass.h


namespace Spellman_SLM_PS_ns
{
/*----- PROTECTED REGION ID(Spellman_SLM_PSClass::classes for dynamic creation) ENABLED START -----*/


/*----- PROTECTED REGION END -----*/	//	Spellman_SLM_PSClass::classes for dynamic creation

//=========================================
//	Define classes for attributes
//=========================================
//	Attribute Voltage class definition
class VoltageAttrib: public Tango::Attr
{
public:
	VoltageAttrib():Attr("Voltage",
			Tango::DEV_USHORT, Tango::READ_WRITE) {};
	~VoltageAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<Spellman_SLM_PS *>(dev))->read_Voltage(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<Spellman_SLM_PS *>(dev))->write_Voltage(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<Spellman_SLM_PS *>(dev))->is_Voltage_allowed(ty);}
};

//	Attribute Amperage class definition
class AmperageAttrib: public Tango::Attr
{
public:
	AmperageAttrib():Attr("Amperage",
			Tango::DEV_USHORT, Tango::READ_WRITE) {};
	~AmperageAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<Spellman_SLM_PS *>(dev))->read_Amperage(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<Spellman_SLM_PS *>(dev))->write_Amperage(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<Spellman_SLM_PS *>(dev))->is_Amperage_allowed(ty);}
};

//	Attribute VoltageMonitor class definition
class VoltageMonitorAttrib: public Tango::Attr
{
public:
	VoltageMonitorAttrib():Attr("VoltageMonitor",
			Tango::DEV_USHORT, Tango::READ) {};
	~VoltageMonitorAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<Spellman_SLM_PS *>(dev))->read_VoltageMonitor(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<Spellman_SLM_PS *>(dev))->is_VoltageMonitor_allowed(ty);}
};

//	Attribute AmperageMonitor class definition
class AmperageMonitorAttrib: public Tango::Attr
{
public:
	AmperageMonitorAttrib():Attr("AmperageMonitor",
			Tango::DEV_USHORT, Tango::READ) {};
	~AmperageMonitorAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<Spellman_SLM_PS *>(dev))->read_AmperageMonitor(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<Spellman_SLM_PS *>(dev))->is_AmperageMonitor_allowed(ty);}
};


//=========================================
//	Define classes for commands
//=========================================
//	Command ResetFaults class definition
class ResetFaultsClass : public Tango::Command
{
public:
	ResetFaultsClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	ResetFaultsClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~ResetFaultsClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<Spellman_SLM_PS *>(dev))->is_ResetFaults_allowed(any);}
};

//	Command RequestStatus class definition
class RequestStatusClass : public Tango::Command
{
public:
	RequestStatusClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	RequestStatusClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~RequestStatusClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<Spellman_SLM_PS *>(dev))->is_RequestStatus_allowed(any);}
};


/**
 *	The Spellman_SLM_PSClass singleton definition
 */

#ifdef _TG_WINDOWS_
class __declspec(dllexport)  Spellman_SLM_PSClass : public Tango::DeviceClass
#else
class Spellman_SLM_PSClass : public Tango::DeviceClass
#endif
{
	/*----- PROTECTED REGION ID(Spellman_SLM_PSClass::Additionnal DServer data members) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	Spellman_SLM_PSClass::Additionnal DServer data members

	public:
		//	write class properties data members
		Tango::DbData	cl_prop;
		Tango::DbData	cl_def_prop;
		Tango::DbData	dev_def_prop;
	
		//	Method prototypes
		static Spellman_SLM_PSClass *init(const char *);
		static Spellman_SLM_PSClass *instance();
		~Spellman_SLM_PSClass();
		Tango::DbDatum	get_class_property(string &);
		Tango::DbDatum	get_default_device_property(string &);
		Tango::DbDatum	get_default_class_property(string &);
	
	protected:
		Spellman_SLM_PSClass(string &);
		static Spellman_SLM_PSClass *_instance;
		void command_factory();
		void attribute_factory(vector<Tango::Attr *> &);
		void pipe_factory();
		void write_class_property();
		void set_default_property();
		void get_class_property();
		string get_cvstag();
		string get_cvsroot();
	
	private:
		void device_factory(const Tango::DevVarStringArray *);
		void create_static_attribute_list(vector<Tango::Attr *> &);
		void erase_dynamic_attributes(const Tango::DevVarStringArray *,vector<Tango::Attr *> &);
		vector<string>	defaultAttList;
		Tango::Attr *get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname);
};

}	//	End of namespace

#endif   //	Spellman_SLM_PS_H
